

trigger: none

resources:
- repo: self

stages:

  - stage: Destroy
    displayName: Destroy with Terraform
    jobs:
    - job: Destroy
      displayName: Destroy
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: TerraformInstaller@1
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      - checkout: self
        displayName: 'Checkout repository'
      - task: TerraformTaskV4@4
        displayName: 'Terraform Init'
        inputs:
          provider: 'aws'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
          backendServiceAWS: 'aws'
          backendAWSBucketName: 'states-tf1'
          backendAWSKey: 'tf/dev/terraform.tfstate'
      - task: TerraformTaskV4@4
        displayName: 'Terraform Destroy'
        inputs:
          provider: 'aws'
          command: 'destroy'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
          commandOptions: '-auto-approve -input=false'
          environmentServiceNameAWS: 'aws'
